/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/': RouteRecordInfo<
      '/dashboard/home/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/HomeChart': RouteRecordInfo<
      '/dashboard/home/components/HomeChart',
      '/dashboard/home/components/HomeChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/HomeDateRangePicker': RouteRecordInfo<
      '/dashboard/home/components/HomeDateRangePicker',
      '/dashboard/home/components/HomeDateRangePicker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/HomePeriodSelect': RouteRecordInfo<
      '/dashboard/home/components/HomePeriodSelect',
      '/dashboard/home/components/HomePeriodSelect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/HomeSales': RouteRecordInfo<
      '/dashboard/home/components/HomeSales',
      '/dashboard/home/components/HomeSales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/HomeStats': RouteRecordInfo<
      '/dashboard/home/components/HomeStats',
      '/dashboard/home/components/HomeStats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/features/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/features/dashboard/home/index.vue': {
      routes:
        | '/dashboard/home/'
      views:
        | never
    }
    'src/features/dashboard/home/components/HomeChart.vue': {
      routes:
        | '/dashboard/home/components/HomeChart'
      views:
        | never
    }
    'src/features/dashboard/home/components/HomeDateRangePicker.vue': {
      routes:
        | '/dashboard/home/components/HomeDateRangePicker'
      views:
        | never
    }
    'src/features/dashboard/home/components/HomePeriodSelect.vue': {
      routes:
        | '/dashboard/home/components/HomePeriodSelect'
      views:
        | never
    }
    'src/features/dashboard/home/components/HomeSales.vue': {
      routes:
        | '/dashboard/home/components/HomeSales'
      views:
        | never
    }
    'src/features/dashboard/home/components/HomeStats.vue': {
      routes:
        | '/dashboard/home/components/HomeStats'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
