/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/': RouteRecordInfo<
      '/dashboard/home/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/AgentChats': RouteRecordInfo<
      '/dashboard/home/components/AgentChats',
      '/dashboard/home/components/AgentChats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/composer/ComposerToolbar': RouteRecordInfo<
      '/dashboard/home/components/composer/ComposerToolbar',
      '/dashboard/home/components/composer/ComposerToolbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/composer/MessageComposer': RouteRecordInfo<
      '/dashboard/home/components/composer/MessageComposer',
      '/dashboard/home/components/composer/MessageComposer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/hero/HeroAvatar': RouteRecordInfo<
      '/dashboard/home/components/hero/HeroAvatar',
      '/dashboard/home/components/hero/HeroAvatar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/hero/HeroSection': RouteRecordInfo<
      '/dashboard/home/components/hero/HeroSection',
      '/dashboard/home/components/hero/HeroSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/suggestions/SuggestionCard': RouteRecordInfo<
      '/dashboard/home/components/suggestions/SuggestionCard',
      '/dashboard/home/components/suggestions/SuggestionCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/home/components/suggestions/SuggestionGrid': RouteRecordInfo<
      '/dashboard/home/components/suggestions/SuggestionGrid',
      '/dashboard/home/components/suggestions/SuggestionGrid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/features/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/features/dashboard/home/index.vue': {
      routes:
        | '/dashboard/home/'
      views:
        | never
    }
    'src/features/dashboard/home/components/AgentChats.vue': {
      routes:
        | '/dashboard/home/components/AgentChats'
      views:
        | never
    }
    'src/features/dashboard/home/components/composer/ComposerToolbar.vue': {
      routes:
        | '/dashboard/home/components/composer/ComposerToolbar'
      views:
        | never
    }
    'src/features/dashboard/home/components/composer/MessageComposer.vue': {
      routes:
        | '/dashboard/home/components/composer/MessageComposer'
      views:
        | never
    }
    'src/features/dashboard/home/components/hero/HeroAvatar.vue': {
      routes:
        | '/dashboard/home/components/hero/HeroAvatar'
      views:
        | never
    }
    'src/features/dashboard/home/components/hero/HeroSection.vue': {
      routes:
        | '/dashboard/home/components/hero/HeroSection'
      views:
        | never
    }
    'src/features/dashboard/home/components/suggestions/SuggestionCard.vue': {
      routes:
        | '/dashboard/home/components/suggestions/SuggestionCard'
      views:
        | never
    }
    'src/features/dashboard/home/components/suggestions/SuggestionGrid.vue': {
      routes:
        | '/dashboard/home/components/suggestions/SuggestionGrid'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
